#!/usr/bin/env bash
# parses an Apache log file that also displays the IP and HTTP code for each visitor, plus the number of occurences.

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
